dist: bionic

language: ruby

services:
  - docker

before_install: 
  - export CI_COMMIT=$(echo ${TRAVIS_COMMIT:0:8})
  - echo $CI_COMMIT
  - docker build -t $DOCKER_HUB_USERNAME/minigoresto:$CI_COMMIT .
  - docker images
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - echo $SSH_PRIVATE_KEY | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

install:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push $DOCKER_HUB_USERNAME/minigoresto:$CI_COMMIT
  - ssh $DEPLOYMENT_HOST "docker pull $DOCKER_HUB_USERNAME/minigoresto:$CI_COMMIT"
  - ssh $DEPLOYMENT_HOST "docker run -d -p $PORT:3000 $DOCKER_HUB_USERNAME/minigoresto:$CI_COMMIT"
  - ssh $DEPLOYMENT_HOST "ufw allow $PORT"